import { Injectable,Logger,OnModuleDestroy,OnModuleInit } from '@nestjs/common'; import { Job,Queue,Worker } from 'bullmq'; import IORedis from 'ioredis';
import { PrismaService } from './prisma.service'; import { OpenWaGateway } from './openwa.gateway'; import { SecretsService } from './secrets.service';
@Injectable() export class AutomationService implements OnModuleInit,OnModuleDestroy {
  private connection?:IORedis; private queue?:Queue; private worker?:Worker; private log=new Logger(AutomationService.name);
  constructor(private db:PrismaService,private openwa:OpenWaGateway,private secrets:SecretsService){}
  onModuleInit(){const url=process.env.REDIS_URL;if(!url){this.log.warn('REDIS_URL no configurado; automatización pausada');return}this.connection=new IORedis(url,{maxRetriesPerRequest:null});this.connection.on('error',e=>this.log.warn('Redis no disponible: '+e.message));this.queue=new Queue('conversation-ai',{connection:this.connection});this.worker=new Worker('conversation-ai',job=>this.process(job),{connection:this.connection,concurrency:4});this.worker.on('error',e=>this.log.warn('Worker Redis: '+e.message));this.worker.on('failed',(job,e)=>this.log.error('Trabajo '+job?.id+' falló: '+e.message))}
  async onModuleDestroy(){await this.worker?.close();await this.queue?.close();this.connection?.disconnect()}
  enqueue(conversationId:string){return this.queue?.add('reply',{conversationId},{jobId:conversationId+'-'+Date.now(),attempts:3,backoff:{type:'exponential',delay:2000},removeOnComplete:100,removeOnFail:100})}
  private async process(job:Job<{conversationId:string}>){const c=await this.db.conversation.findUnique({where:{id:job.data.conversationId},include:{lead:true,agent:true,session:true,messages:{orderBy:{createdAt:'desc'},take:20}}});if(!c||c.mode!=='AI_ACTIVE'||!c.agent?.aiEnabled||c.agent.status!=='ACTIVE'||!c.session.providerSessionId)return;const provider=await this.db.llmProvider.findFirst({where:{enabled:true},orderBy:{createdAt:'desc'}});if(!provider)return;const properties=await this.db.property.findMany({where:{organizationId:c.organizationId,status:'AVAILABLE'},take:20,orderBy:{updatedAt:'desc'}});const history=c.messages.reverse().map(m=>(m.direction==='INBOUND'?'Cliente':'Asesor')+': '+(m.text||'')).join('\n');const inventory=properties.map(p=>[p.title,p.operationType,p.location,p.price+' '+p.currency,(p.bedrooms||0)+' rec',p.url||''].join(' | ')).join('\n');const prompt=(c.agent.systemInstructions||'Eres un asesor inmobiliario claro y útil.')+'\nNo inventes propiedades, precios o disponibilidad. Usa únicamente este inventario:\n'+(inventory||'No hay propiedades disponibles; indícalo con honestidad.')+'\nLead: '+(c.lead.name||c.lead.phone)+'\nHistorial:\n'+history;const base=(provider.baseUrl||'https://api.openai.com/v1').replace(/\/$/,'');const response=await fetch(base+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+this.secrets.decrypt(provider.encryptedApiKey)},body:JSON.stringify({model:provider.model,messages:[{role:'system',content:prompt},{role:'user',content:'Responde al último mensaje del cliente.'}],temperature:.3})});if(!response.ok)throw new Error('LLM '+response.status);const json:any=await response.json();const text=String(json.choices?.[0]?.message?.content||'').trim();if(!text)return;const fresh=await this.db.conversation.findUnique({where:{id:c.id}});if(fresh?.mode!=='AI_ACTIVE')return;const sent:any=await this.openwa.sendText({providerSessionId:c.session.providerSessionId,chatId:c.lead.phone,text});await this.db.message.create({data:{conversationId:c.id,providerMessageId:String(sent?.id||sent?.messageId||'ai-'+Date.now()),direction:'OUTBOUND',type:'text',text,status:'SENT',authorType:'AI',origin:'CRM'}});await this.db.conversation.update({where:{id:c.id},data:{lastMessageAt:new Date()}})}
}
