import { BadRequestException, Body, ConflictException, Controller, ForbiddenException, Get, Param, Patch, Post } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { hash } from 'bcryptjs'; import { createHash, randomBytes } from 'crypto';
import { CurrentUser, AuthUser, Public, Roles } from './auth'; import { PrismaService } from './prisma.service';
@Controller('organizations')
export class OrganizationsController {
  constructor(private db:PrismaService){}
  @Get() list(@CurrentUser() user:AuthUser){return user.isSuperAdmin?this.db.organization.findMany({include:{_count:{select:{members:true,agents:true,sessions:true,leads:true}}},orderBy:{createdAt:'desc'}}):this.db.organization.findMany({where:{members:{some:{userId:user.id}}}})}
  @Roles('SUPER_ADMIN') @Post() async create(@CurrentUser() user:AuthUser,@Body() body:{name:string;slug:string;ownerEmail:string;ownerName?:string;ownerPassword?:string;timezone?:string}){
    const name=body.name?.trim();
    const slug=body.slug?.trim().toLowerCase();
    const ownerEmail=body.ownerEmail?.trim().toLowerCase();
    if(!name||!slug||!ownerEmail)throw new BadRequestException('Nombre, slug y correo del propietario son obligatorios');
    if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw new BadRequestException('El slug solo puede contener letras minúsculas, números y guiones');
    if(body.ownerPassword&&body.ownerPassword.length<8)throw new BadRequestException('La contraseña temporal debe tener al menos 8 caracteres');
    const passwordHash=body.ownerPassword?await hash(body.ownerPassword,12):undefined;
    try{
      return await this.db.$transaction(async tx=>{
        const owner=await tx.user.upsert({where:{email:ownerEmail},create:{email:ownerEmail,name:body.ownerName?.trim()||ownerEmail,passwordHash,status:passwordHash?'ACTIVE':'INVITED'},update:passwordHash?{name:body.ownerName?.trim()||undefined,passwordHash,status:'ACTIVE'}:{}});
        const memberStatus=passwordHash?'ACTIVE':'INVITED';
        const organization=await tx.organization.create({data:{name,slug,timezone:body.timezone?.trim()||'America/Mexico_City',members:{create:{userId:owner.id,role:'OWNER',status:memberStatus}}}});
        let token:string|undefined;
        if(!passwordHash){token=randomBytes(32).toString('hex');await tx.invitation.create({data:{organizationId:organization.id,email:owner.email,role:'OWNER',tokenHash:createHash('sha256').update(token).digest('hex'),invitedById:user.id,expiresAt:new Date(Date.now()+7*86400000)}})}
        await tx.auditLog.create({data:{organizationId:organization.id,userId:user.id,action:'ORGANIZATION_CREATED',entityType:'Organization',entityId:organization.id}});
        return {organization,...(token?{invitationToken:token}:{})};
      });
    }catch(error){
      if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('Ya existe una agencia con ese slug');
      throw error;
    }
  }
  @Patch(':id/status') async status(@CurrentUser() user:AuthUser,@Param('id') id:string,@Body() body:{status:'ACTIVE'|'SUSPENDED'|'ARCHIVED'}){if(!user.isSuperAdmin)throw new ForbiddenException('Solo superadministración');const result=await this.db.organization.update({where:{id},data:{status:body.status}});await this.audit(id,user.id,'ORGANIZATION_STATUS_CHANGED','Organization',id,{status:body.status});return result}
  @Post(':id/invitations') @Roles('OWNER','ADMIN') async invite(@CurrentUser() user:AuthUser,@Param('id') organizationId:string,@Body() body:{email:string;role:'ADMIN'|'SUPERVISOR'|'ADVISOR'}){if(!user.isSuperAdmin&&user.organizationId!==organizationId)throw new ForbiddenException('Agencia inválida');const token=randomBytes(32).toString('hex');await this.db.invitation.create({data:{organizationId,email:body.email.trim().toLowerCase(),role:body.role,tokenHash:createHash('sha256').update(token).digest('hex'),invitedById:user.id,expiresAt:new Date(Date.now()+7*86400000)}});return {token,expiresIn:'7d'}}
  @Post(':id/members') @Roles('OWNER','ADMIN') async addMember(@CurrentUser() actor:AuthUser,@Param('id') organizationId:string,@Body() body:{email:string;name:string;password:string;role:'OWNER'|'ADMIN'|'SUPERVISOR'|'ADVISOR'}){if(!actor.isSuperAdmin&&actor.organizationId!==organizationId)throw new ForbiddenException('Agencia inválida');if(!body.password||body.password.length<8)throw new BadRequestException('La contraseña debe tener al menos 8 caracteres');if(!['OWNER','ADMIN','SUPERVISOR','ADVISOR'].includes(body.role))throw new BadRequestException('Rol inválido');const email=body.email.trim().toLowerCase();const passwordHash=await hash(body.password,12);return this.db.$transaction(async tx=>{const memberUser=await tx.user.upsert({where:{email},create:{email,name:body.name.trim()||email,passwordHash,status:'ACTIVE'},update:{name:body.name.trim()||undefined,passwordHash,status:'ACTIVE'}});const membership=await tx.organizationMember.upsert({where:{organizationId_userId:{organizationId,userId:memberUser.id}},create:{organizationId,userId:memberUser.id,role:body.role,status:'ACTIVE'},update:{role:body.role,status:'ACTIVE'}});await tx.auditLog.create({data:{organizationId,userId:actor.id,action:'ORGANIZATION_MEMBER_UPSERTED',entityType:'User',entityId:memberUser.id}});return {user:{id:memberUser.id,email:memberUser.email,name:memberUser.name},membership}})}
  @Patch(':id/members/:userId') @Roles('OWNER','ADMIN') async updateMember(@CurrentUser() actor:AuthUser,@Param('id') organizationId:string,@Param('userId') userId:string,@Body() body:{name?:string;password?:string;role?:'OWNER'|'ADMIN'|'SUPERVISOR'|'ADVISOR';status?:'INVITED'|'ACTIVE'|'DISABLED'}){if(!actor.isSuperAdmin&&actor.organizationId!==organizationId)throw new ForbiddenException('Agencia inválida');if(body.password&&body.password.length<8)throw new BadRequestException('La contraseña debe tener al menos 8 caracteres');if(body.role&&!['OWNER','ADMIN','SUPERVISOR','ADVISOR'].includes(body.role))throw new BadRequestException('Rol inválido');const passwordHash=body.password?await hash(body.password,12):undefined;return this.db.$transaction(async tx=>{const memberUser=await tx.user.update({where:{id:userId},data:{name:body.name?.trim(),passwordHash,status:body.password?'ACTIVE':body.status}});const membership=await tx.organizationMember.update({where:{organizationId_userId:{organizationId,userId}},data:{role:body.role,status:body.password?'ACTIVE':body.status}});await tx.auditLog.create({data:{organizationId,userId:actor.id,action:'ORGANIZATION_MEMBER_UPDATED',entityType:'User',entityId:userId}});return {user:{id:memberUser.id,email:memberUser.email,name:memberUser.name},membership}})}
  @Public() @Post('invitations/accept') async accept(@Body() body:{token:string;name:string;password:string}){const tokenHash=createHash('sha256').update(body.token).digest('hex');const invite=await this.db.invitation.findUnique({where:{tokenHash}});if(!invite||invite.acceptedAt||invite.expiresAt<new Date())throw new ForbiddenException('Invitación inválida o vencida');const passwordHash=await hash(body.password,12);const user=await this.db.user.upsert({where:{email:invite.email},create:{email:invite.email,name:body.name,passwordHash,status:'ACTIVE'},update:{name:body.name,passwordHash,status:'ACTIVE'}});await this.db.organizationMember.upsert({where:{organizationId_userId:{organizationId:invite.organizationId,userId:user.id}},create:{organizationId:invite.organizationId,userId:user.id,role:invite.role,status:'ACTIVE'},update:{role:invite.role,status:'ACTIVE'}});await this.db.invitation.update({where:{id:invite.id},data:{acceptedAt:new Date()}});return {accepted:true}}
  @Get(':id/members') listMembers(@CurrentUser() user:AuthUser,@Param('id') organizationId:string){if(!user.isSuperAdmin&&user.organizationId!==organizationId)throw new ForbiddenException('Agencia inválida');return this.db.organizationMember.findMany({where:{organizationId},include:{user:{select:{id:true,email:true,name:true,status:true}}}})}
  private audit(organizationId:string,userId:string,action:string,entityType:string,entityId:string,metadata?:object){return this.db.auditLog.create({data:{organizationId,userId,action,entityType,entityId,metadata}})}
}
