import { Body,Controller,Get,Param,Post } from '@nestjs/common'; import { OpenWaGateway } from './openwa.gateway'; import { PrismaService } from './prisma.service'; import { TenantId } from './tenant';
@Controller('whatsapp/sessions') export class WhatsappController {
  constructor(private openwa:OpenWaGateway,private db:PrismaService){}
  @Get() list(@TenantId() organizationId:string){return this.db.whatsappSession.findMany({where:{organizationId,status:{not:'DELETED'}},include:{agent:true},orderBy:{createdAt:'desc'}})}
  @Post() async create(@TenantId() organizationId:string,@Body() body:{name:string}){const local=await this.db.whatsappSession.create({data:{organizationId,name:body.name,status:'CREATING'}});try{const remote:any=await this.openwa.createSession(local.id);const providerSessionId=String(remote?.id||remote?.sessionId||local.id);const webhookUrl=(process.env.PUBLIC_API_URL||process.env.APP_URL||'').replace(/\/$/,'')+'/api/v1/integrations/openwa/webhook';if(webhookUrl.startsWith('http'))await this.openwa.createWebhook(providerSessionId,webhookUrl,process.env.OPENWA_WEBHOOK_SECRET);await this.openwa.startSession(providerSessionId);return this.db.whatsappSession.update({where:{id:local.id},data:{providerSessionId,status:'QR_REQUIRED'}})}catch(error){await this.db.whatsappSession.update({where:{id:local.id},data:{status:'FAILED'}});throw error}}
  @Post(':id/start') async start(@TenantId() organizationId:string,@Param('id') id:string){const s=await this.db.whatsappSession.findFirstOrThrow({where:{id,organizationId}});const result=await this.openwa.startSession(s.providerSessionId||s.id);await this.db.whatsappSession.update({where:{id},data:{status:'STARTING'}});return result}
  @Get(':id/qr') async qr(@TenantId() organizationId:string,@Param('id') id:string){const s=await this.db.whatsappSession.findFirstOrThrow({where:{id,organizationId}});return this.openwa.getQr(s.providerSessionId||s.id)}
  @Get(':id/status') async status(@TenantId() organizationId:string,@Param('id') id:string){const s=await this.db.whatsappSession.findFirstOrThrow({where:{id,organizationId}});const result:any=await this.openwa.getStatus(s.providerSessionId||s.id);const value=String(result?.status||result?.state||'').toUpperCase();const mapped=value.includes('CONNECT')?'CONNECTED':value.includes('QR')?'QR_REQUIRED':value.includes('START')?'STARTING':'DISCONNECTED';await this.db.whatsappSession.update({where:{id},data:{status:mapped as any,phoneNumber:result?.phoneNumber||result?.phone||undefined}});return result}
}
